"""Initial migration - scanned_events and users tables

Revision ID: 5f5f4e873b5b
Revises: 
Create Date: 2026-02-03 12:54:36.617997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f5f4e873b5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scanned_events', 'uid',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Identifiant unique pour déduplication',
               existing_nullable=False)
    op.alter_column('scanned_events', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Latitude GPS obtenue via géocodage Google Places',
               existing_nullable=True)
    op.alter_column('scanned_events', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Longitude GPS obtenue via géocodage Google Places',
               existing_nullable=True)
    op.alter_column('scanned_events', 'place_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Identifiant Google Places du lieu',
               existing_nullable=True)
    op.alter_column('scanned_events', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               type_=sa.Float(),
               comment=None,
               existing_comment='Note Google Places (0.0 à 5.0)',
               existing_nullable=True)
    op.alter_column('scanned_events', 'raw_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Données brutes JSON complètes de l'événement",
               existing_nullable=True)
    op.alter_column('scanned_events', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_scanned_events_begin_date'), table_name='scanned_events')
    op.drop_index(op.f('idx_scanned_events_category'), table_name='scanned_events')
    op.drop_index(op.f('idx_scanned_events_city'), table_name='scanned_events')
    op.drop_index(op.f('idx_scanned_events_coords'), table_name='scanned_events')
    op.drop_index(op.f('idx_scanned_events_private'), table_name='scanned_events')
    op.drop_index(op.f('idx_scanned_events_raw_json'), table_name='scanned_events', postgresql_using='gin')
    op.drop_index(op.f('idx_scanned_events_uid'), table_name='scanned_events')
    op.drop_index(op.f('idx_scanned_events_user'), table_name='scanned_events')
    op.drop_constraint(op.f('scanned_events_uid_key'), 'scanned_events', type_='unique')
    op.create_index(op.f('ix_scanned_events_is_private'), 'scanned_events', ['is_private'], unique=False)
    op.create_index(op.f('ix_scanned_events_uid'), 'scanned_events', ['uid'], unique=True)
    op.drop_table_comment(
        'scanned_events',
        existing_comment='Table des événements scrapés depuis Infolocale.fr',
        schema=None
    )
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_table_comment(
        'users',
        existing_comment='Table des utilisateurs du système',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Table des utilisateurs du système',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'scanned_events',
        'Table des événements scrapés depuis Infolocale.fr',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_scanned_events_uid'), table_name='scanned_events')
    op.drop_index(op.f('ix_scanned_events_is_private'), table_name='scanned_events')
    op.create_unique_constraint(op.f('scanned_events_uid_key'), 'scanned_events', ['uid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_scanned_events_user'), 'scanned_events', ['user_id'], unique=False)
    op.create_index(op.f('idx_scanned_events_uid'), 'scanned_events', ['uid'], unique=False)
    op.create_index(op.f('idx_scanned_events_raw_json'), 'scanned_events', ['raw_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_scanned_events_private'), 'scanned_events', ['is_private'], unique=False)
    op.create_index(op.f('idx_scanned_events_coords'), 'scanned_events', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('idx_scanned_events_city'), 'scanned_events', ['city'], unique=False)
    op.create_index(op.f('idx_scanned_events_category'), 'scanned_events', ['category'], unique=False)
    op.create_index(op.f('idx_scanned_events_begin_date'), 'scanned_events', ['begin_date'], unique=False)
    op.alter_column('scanned_events', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('scanned_events', 'raw_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Données brutes JSON complètes de l'événement",
               existing_nullable=True)
    op.alter_column('scanned_events', 'rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=2, scale=1),
               comment='Note Google Places (0.0 à 5.0)',
               existing_nullable=True)
    op.alter_column('scanned_events', 'place_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Identifiant Google Places du lieu',
               existing_nullable=True)
    op.alter_column('scanned_events', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Longitude GPS obtenue via géocodage Google Places',
               existing_nullable=True)
    op.alter_column('scanned_events', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Latitude GPS obtenue via géocodage Google Places',
               existing_nullable=True)
    op.alter_column('scanned_events', 'uid',
               existing_type=sa.VARCHAR(length=100),
               comment='Identifiant unique pour déduplication',
               existing_nullable=False)
    # ### end Alembic commands ###
