"""Initial migration - create tables

Revision ID: 9bc33c1d22ce
Revises: 
Create Date: 2026-02-04 11:28:46.618232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bc33c1d22ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reset_sent_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('scanned_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('begin_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pricing', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('artists', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('sponsors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('location_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('zipcode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('place_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('place_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('schema_org_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanned_events_is_private'), 'scanned_events', ['is_private'], unique=False)
    op.create_index(op.f('ix_scanned_events_uid'), 'scanned_events', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanned_events_uid'), table_name='scanned_events')
    op.drop_index(op.f('ix_scanned_events_is_private'), table_name='scanned_events')
    op.drop_table('scanned_events')
    op.drop_table('users')
    # ### end Alembic commands ###
